server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: root5687
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      default-zone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}